[package]
name = "edgeware-rpc-debug"
authors = [ "PureStake" ]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
futures = { version = "0.3", features = [ "compat" ] }
hex-literal = "0.3.4"
jsonrpsee = { version = "0.13.1", default-features = false, features = [ "macros", "server" ] }
tokio = { version = "1.18.2", features = [ "sync", "time" ] }

# Edgeware (copied from Moonbeam)
edgeware-client-evm-tracing = { path = "../../evm-tracing" }
edgeware-rpc-core-debug = { path = "../../rpc-core/debug" }
edgeware-rpc-core-types = { path = "../../rpc-core/types" }
edgeware-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }

# Frontier
ethereum = { version = "0.12.0", default-features = false, features = [ "with-codec" ] }
ethereum-types = "0.13.1"
evm = { git = "https://github.com/rust-blockchain/evm", branch = "master", default-features = false, features = [ "with-codec" ] } #
fc-consensus = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.22" }
fc-db = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.22" }
fc-rpc = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.22", features = [ "rpc_binary_search_estimate" ] }
fp-rpc = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.22" }
