[package]
name = "edgeware-rpc-primitives-txpool"
authors = [ "PureStake" ]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.6.0"

[dependencies]
ethereum = { workspace = true, default-features = false, features = [ "with-codec" ] }

# Substrate
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, features = [ "derive" ]}
sp-api = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[features]
default = [ "std" ]
std = [
	"ethereum/std",
	"scale-info/std",
	"sp-api/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
